server:
  port: 8761
spring:
  application:
    name: discovery
#  config:
#    import: "http://localhost:8888/"
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

test:
  value: not imported
