server:
  port: 8761
spring:
  application:
    name: discovery
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      profile: main
      fail-fast: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

test:
  value: not imported
  
management:
  # endpoint 노출
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans,info,configprops"
      base-path: /actuator
  # endpoint 활성화/비활성화
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
      tags:
        application: ${spring.application.name}
    prometheus:
      enabled: true
